spring:
  application:
    name: searchService
  config:
    import: configserver:http://${serverUrl}:8050/
  cloud:
    config:
      profile: ${profile}

serverUrl: config-server-prod  #localhost or config-server-prod
profile: prod # dev or prod
