spring:
  application:
    name: salesService
  config:
    import: configserver:http://${serverUrl}:8050/
  cloud:
    config:
      profile: ${profile}

serverUrl: localhost  #localhost or config-server-prod
profile: dev # dev or prod
